all: flop cheap doc libfspp.a

libfspp.a:
	cd fspp
	make libfspp.a

flop:
	cd flop
	make flop

cheap:
	cd cheap
	make cheap

doc: flopdoc cheapdoc

flopdoc:
	doxygen doxyconfig.flop

cheapdoc:
	doxygen doxyconfig.cheap
